### ISSUE TITLE
请教如果我想得到所有地级市的电子围栏应该如何操作？

### ISSUE THREAD

**Issue by homecls** [Vonng/adcode#1]
首先，这真的是一个很棒的工作。
请教如果我想得到所有地级市的电子围栏应该如何操作？

**Comment by Vonng** [comment]
st_union

发自我的 iPhone

在 2018年12月21日，09:33，homecls <notifications@github.com<mailto:notifications@github.com>> 写道：


首先，这真的是一个很棒的工作。
请教如果我想得到所有地级市的电子围栏应该如何操作？

**Comment by homecls** [comment]
非常感谢，。不是太懂、我回去先研究一下。谢谢！

**Comment by homecls** [comment]
非常感谢！我大概明白了，实际是对两个集合进行合并。
