### ISSUE TITLE
西藏那曲的代码错了

### ISSUE THREAD

**Issue by lispc** [Vonng/adcode#2]
2017年行政区划改了，从“那曲地区”变成了"那曲市"。
http://xzqh.mca.gov.cn/ssdescription?dcps=54&dcpid=2017
https://zh.wikipedia.org/wiki/%E9%82%A3%E6%9B%B2%E5%B8%82
从 542400 改成 540600

**Comment by Vonng** [comment]
为了保持时间一致性，那只能下个版本改了…，近期会更新一下。
