### ISSUE TITLE
后续数据更新

### ISSUE THREAD

**Issue by catcallxw** [Vonng/adcode#4]
你好，你的这份数据对我们车联网业务非常有用，不知道后续更新的数据是否在做？是否需要一起开发？

**Comment by catcallxw** [comment]
希望得到你的回复

**Comment by Vonng** [comment]
> 希望得到你的回复

这个是2018年的，2020年的新数据应该已经出来了。
是从国家统计局与民政部和高德地图拼出来的，需要比对民政部的区划更新通知，还挺费事。
最近比较忙，实在没时间更新哈，如果您愿意帮助PR更正则感谢之至。
